cloud:
  aws:
    credentials:
      accessKey: AKIAUTGPUHQJHGPL63HO
      secretKey: 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
    s3:
      bucket: wuga
    region:
      static: ap-northeast-2
    stack:
      auto: false
    util:
      EC2MetadataUtils: error